Obtaining file:///cluster/home/wzy/vim_mos/causal-conv1d
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
